version: '3.7'

services:
  dev:
    image: sandring/blog:${PLATFORM}-dev
    container_name: ${CONTAINER_NAME}
    entrypoint: tail -f /dev/null
    volumes:
      - .:/usr/src/app
      - ~/.ssh:/root/.ssh:ro
    restart: unless-stopped
  deploy:
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://172.17.0.1:${CONTAINER_PORT}']
      interval: 10m
      retries: 30
      start_period: 60s
    build:
      dockerfile: docker/deploy/dockerfile
      context: .
      args:
        PLATFORM: ${PLATFORM}
    container_name: ${CONTAINER_NAME}_deploy
    entrypoint: sh docker/deploy/run.sh
    hostname: root
    ports:
      - '${CONTAINER_PORT}:8000'
    restart: unless-stopped
    working_dir: /usr/src/app
    environment:
      TZ: 'Asia/Seoul'
