# Generated by Django 4.1.7 on 2023-03-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
