# Generated by Django 4.1.5 on 2023-01-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_saved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(default="", max_length=256),
        ),
    ]
