# Generated by Django 4.1.5 on 2023-01-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_article_is_saved_alter_article_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
